---
# https://hub.docker.com/r/jellyfin/jellyfin
version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Berlin
      - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - /srv/mergerfs/config/appdata/jellyfin:/config
      - /srv/mergerfs/pool/share_media/:/data
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    networks:
      - htpc
    restart: unless-stopped

networks:
  htpc:
    external: true